#!/usr/bin/env bash
# bootstrap-worktree.sh - Provisions an isolated agent worktree with its own cargo target directory
set -euo pipefail

if [[ $# -lt 2 ]]; then
  printf 'Usage: %s <agent-name> <track> [base-branch]\n' "$0" >&2
  printf 'Example: %s storage storage main\n' "$0" >&2
  exit 1
fi

agent_name="$1"
track="$2"
base_branch="${3:-main}"

repo_root="$(git rev-parse --show-toplevel 2>/dev/null || pwd)"
cd "$repo_root"

branch_name="agent/${track}/${agent_name}"
parent_dir="$(cd "$repo_root/.." && pwd)"
worktrees_base="$parent_dir/vdb-worktrees"
worktree_dir="$worktrees_base/vdb-agent-${agent_name}"
target_dir="$repo_root/target-${agent_name}"

printf '=== Provisioning Worktree for Agent "%s" (Track: "%s") ===\n' "$agent_name" "$track"
printf '  Branch:        %s\n' "$branch_name"
printf '  Worktree Path: %s\n' "$worktree_dir"
printf '  Cargo Target:  %s\n' "$target_dir"

if [[ -d "$worktree_dir" ]]; then
  printf 'Warning: Worktree directory already exists at %s\n' "$worktree_dir"
  exit 0
fi

mkdir -p "$worktrees_base" "$target_dir"

if git show-ref --quiet --heads "$branch_name"; then
  printf '  Checking out existing branch "%s"...\n' "$branch_name"
  git worktree add "$worktree_dir" "$branch_name"
else
  printf '  Creating new branch "%s" from "%s"...\n' "$branch_name" "$base_branch"
  git worktree add -b "$branch_name" "$worktree_dir" "$base_branch"
fi

mkdir -p "$worktree_dir/.cargo"
cat > "$worktree_dir/.cargo/config.toml" <<EOF
# Auto-generated by bootstrap-worktree.sh - Isolated target directory
[build]
target-dir = "$target_dir"
EOF


printf '  -> Configured isolated target-dir in %s/.cargo/config.toml\n' "$worktree_dir"
printf '>>> Worktree Ready for Agent "%s"! <<<\n' "$agent_name"
printf '  cd "%s"\n' "$worktree_dir"
