# bootstrap-worktree.ps1 - Provisions an isolated agent worktree with its own cargo target directory
[CmdletBinding()]
param(
    [Parameter(Mandatory=$true, Position=0)]
    [string]$AgentName,

    [Parameter(Mandatory=$true, Position=1)]
    [string]$Track,

    [Parameter(Position=2)]
    [string]$BaseBranch = "main"
)

$ErrorActionPreference = "Stop"

$repoRoot = (git rev-parse --show-toplevel 2>$null)
if (-not $repoRoot) {
    Write-Error "Must run inside a Git repository."
    exit 1
}
cd $repoRoot

$branchName = "agent/$Track/$AgentName"
$worktreesBase = Join-Path (Split-Path $repoRoot -Parent) "vdb-worktrees"
$worktreeDir = Join-Path $worktreesBase "vdb-agent-$AgentName"
$targetDir = Join-Path $repoRoot "target-$AgentName"

Write-Host "=== Provisioning Worktree for Agent '$AgentName' (Track: '$Track') ===" -ForegroundColor Cyan
Write-Host "  Repository Root: $repoRoot" -ForegroundColor Gray
Write-Host "  Branch:          $branchName" -ForegroundColor Gray
Write-Host "  Worktree Path:   $worktreeDir" -ForegroundColor Gray
Write-Host "  Cargo Target:    $targetDir" -ForegroundColor Gray

if (Test-Path $worktreeDir) {
    Write-Warning "Worktree directory already exists at $worktreeDir."
    exit 0
}

# Create base folders
New-Item -ItemType Directory -Path $worktreesBase -Force | Out-Null
New-Item -ItemType Directory -Path $targetDir -Force | Out-Null

# Check if branch exists
$branchList = (git branch --list $branchName | Out-String).Trim()
$branchExists = $branchList.Length -gt 0

if ($branchExists) {
    Write-Host "  Checking out existing branch '$branchName'..." -ForegroundColor Gray
    git worktree add $worktreeDir $branchName
} else {
    Write-Host "  Creating new branch '$branchName' from '$BaseBranch'..." -ForegroundColor Gray
    git worktree add -b $branchName $worktreeDir $BaseBranch
}

if ($LASTEXITCODE -ne 0) {
    Write-Error "Failed to create worktree."
    exit 1
}

# Inject isolated .cargo/config.toml
$cargoConfigDir = Join-Path $worktreeDir ".cargo"
New-Item -ItemType Directory -Path $cargoConfigDir -Force | Out-Null
$cargoConfigFile = Join-Path $cargoConfigDir "config.toml"

$targetDirForward = ($targetDir -replace '\\', '/')
$targetContent = @"
# Auto-generated by bootstrap-worktree.ps1 - Isolated target directory
[build]
target-dir = "$targetDirForward"
"@

Set-Content -Path $cargoConfigFile -Value $targetContent -Encoding UTF8
Write-Host "  -> Configured isolated target-dir in $cargoConfigFile" -ForegroundColor Green


Write-Host "`n>>> Worktree Ready for Agent '$AgentName'! <<<" -ForegroundColor Green
Write-Host "To work in this worktree:" -ForegroundColor Yellow
Write-Host "  cd `"$worktreeDir`"" -ForegroundColor Yellow
exit 0
